Repository metwork-framework/mfextaddon_python2, pull requests merged in 2020-07, with the labels that each got.

#39 No tcltk
  integration_tests/0004_test_import_python2/.layerapi2_dependencies
  layers/layer2_python2/.layerapi2_dependencies
Labels: backport-to-1.0

#41 build: fix log --help and python3_wrapper --help
  layers/layer1_python2_core/0000_adm/python3_wrapper
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
Labels: Merge Now, backport-to-1.0

#43 build: acquisition update
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
Labels: backport-to-1.0

#48 Integration
  .mergify.yml
  docs/.gitignore
  layers/layer2_python2/0500_extra_python_packages/requirements2.txt
  mkdocs.yml
Labels: Status: Merge Now, Status: Review Needed, Type: Maintenance
